spring:
  datasource:
    url: jdbc:sqlite::resource:chatdb.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC


mybatis:
  typeAliasesPackage: org.spring.springboot.domain
  mapperLocations: classpath:mapper/*

log4j:
  logger:
    com.ibatis: DEBUG
    com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    com.ibatis.common.jdbc.ScriptRunner: DEBUG
    com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
    Java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG